linklist/urls.py
from django.contrib import admin
from django.urls import include, path
from bootstrap_customizer import urls as bootstrap_customizer_urls

urlpatterns = [
    path('', include('links.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bootstrap_customizer/', include(bootstrap_customizer_urls)),
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('editlist', views.edit_list_view, name="editlist"),
    path('success', views.success, name='success'),
    path('<pk>/delete', views.delete_link, name='delete_link'),
    path('<pk>/deletelinkconfirm', views.delete_link_confirm, name='deletelinkconfirm'),
    path('<pk>/deletegroup', views.delete_group, name='delete_group'),
    path('<pk>/deletegroupconfirm', views.delete_group_confirm, name='deletegroupconfirm'),
    path('<pk>/movelinkup', views.move_link_up, name='movelinkup'),
    path('<pk>/movelinkdown', views.move_link_down, name='movelinkdown'),
    path('<pk>/movegroupup', views.move_group_up, name='movegroupup'),
    path('<pk>/movegroupdown', views.move_group_down, name='movegroupdown'),
]

links/models.py
from django.db import models
from urllib.parse import urlparse

# Create your models here.

def get_group_order():
    """Get the largest used number from LinkGroup order_by
       Return 0 if there are no groups"""
    largest = LinkGroup.objects.all().order_by('group_order').last()
    if not largest:
        return 0
    else:
        return largest.group_order+1

def get_link_order():
    """Get the largest used number from LinkGroup order_by
    Return 0 if there are no groups"""
    largest = Link.objects.all().order_by('link_order').last()
    if not largest:
        return 0
    else:
        return largest.link_order+1

class LinkGroup(models.Model):
    group_name = models.CharField(max_length=256)
    group_order = models.IntegerField(default=get_group_order)

    def __str__(self):
        return f"{self.group_name}"

    class Meta:
        """Order LinkGroups by this field instead of by id, which is the default"""
        ordering = ['group_order']

class Link(models.Model):
    group = models.ForeignKey(LinkGroup, blank=True, null=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=2048)
    text = models.CharField(max_length=256)
    favicon = models.CharField(max_length=2048, default="")
    link_order = models.IntegerField(default=get_link_order)

    def __str__(self):
        return f"{self.text} {self.url}"

    def get_domain(self):
        return urlparse(self.url).netloc

    def save(self, *args, **kwargs):
        if self.favicon == "":
            self.favicon = f"https://www.google.com/s2/favicons?domain={ self.get_domain() }&sz=32"
        super().save(*args, **kwargs)

    class Meta:
        """Order Links by this field"""
        ordering = ['link_order']

links/forms.py
from django import forms
from .models import *

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['url', 'text', 'group']

class GroupForm(forms.ModelForm):
    class Meta:
        model = LinkGroup
        fields = ['group_name',]

links/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required

from .models import Link, LinkGroup
from .forms import LinkForm, GroupForm

# Create your views here.

class IndexView(generic.ListView):
    template_name = "links/link_list.html"
    context_object_name = "groups_list"

    def get_queryset(self):
        return LinkGroup.objects.all()

@login_required
def edit_list_view(request):
    if request.method == 'POST':
        if 'add_link' in request.POST:
            form = LinkForm(request.POST)
            if form.is_valid():
                form.save()
                #return redirect('links:success')
        if 'add_group' in request.POST:
            form = GroupForm(request.POST)
            if form.is_valid():
                form.save()

    return render(request, 'links/edit_list.html', {'groups_list': LinkGroup.objects.all(), 'link_form': LinkForm(), 'group_form': GroupForm()})

def success(request):
    return HttpResponse('Link Added.')

@login_required
def delete_link(request, pk):
    return render(request, 'links/delete_link.html', {'link': Link.objects.get(pk=pk)})

@login_required
def delete_link_confirm(request, pk):
    Link.objects.get(pk=pk).delete()
    return redirect('links:editlist')

@login_required
def delete_group(request, pk):
    return render(request, 'links/delete_group.html', {'group': LinkGroup.objects.get(pk=pk)})

@login_required
def delete_group_confirm(request, pk):
    LinkGroup.objects.get(pk=pk).delete()
    return redirect('links:editlist')

@login_required
def move_link_up(request, pk):
    #find the link we're looking for
    moving_link = Link.objects.get(pk=pk)
    # get its link_order
    moving_link_order = moving_link.link_order
    # and group
    moving_link_group = moving_link.group
    # look up links with the same group and a lower link_order
    links = Link.objects.filter(group=moving_link_group, link_order__lt=moving_link_order)
    if links.count() == 0:
        # If there aren't any, error out
        #return HttpResponse(f"No links above {moving_link_order}")
        return redirect('links:editlist')
    else:
        # If there's at least one, get the last one
        above_link = links.last()
        # Swap the link_orders, and save the links.
        moving_link.link_order = above_link.link_order
        moving_link.save()
        above_link.link_order = moving_link_order
        above_link.save()
        return redirect('links:editlist')

@login_required
def move_link_down(request, pk):
    moving_link = Link.objects.get(pk=pk)
    moving_link_order = moving_link.link_order
    moving_link_group = moving_link.group
    links = Link.objects.filter(group=moving_link_group, link_order__gt=moving_link_order)
    if links.count() == 0:
        #return HttpResponse(f"No links below {moving_link_order}")
        return redirect('links:editlist')
    else:
        above_link = links.first()
        moving_link.link_order = above_link.link_order
        moving_link.save()
        above_link.link_order = moving_link_order
        above_link.save()
        return redirect('links:editlist')

@login_required
def move_group_up(request, pk):
    moving_group = LinkGroup.objects.get(pk=pk)
    moving_group_order = moving_group.group_order
    groups = LinkGroup.objects.filter(group_order__lt=moving_group_order)
    if groups.count() == 0:
        return redirect('links:editlist')
    else:
        above_group = groups.last()
        moving_group.group_order = above_group.group_order
        moving_group.save()
        above_group.group_order = moving_group_order
        above_group.save()
        return redirect('links:editlist')

@login_required
def move_group_down(request, pk):
    moving_group = LinkGroup.objects.get(pk=pk)
    moving_group_order = moving_group.group_order
    groups = LinkGroup.objects.filter(group_order__gt=moving_group_order)
    if groups.count() == 0:
        return redirect('links:editlist')
    else:
        above_group = groups.first()
        moving_group.group_order = above_group.group_order
        moving_group.save()
        above_group.group_order = moving_group_order
        above_group.save()
        return redirect('links:editlist')

links/templates/links/delete_group.html
{% load bootstrap_customizer %}<!doctype html>
<html>
    <head>
        <title>Link List</title>
        <style lang="css">{% bootstrap_theme_css_above_the_fold %}</style>
    </head>
    <body>
        <link rel="stylesheet" type="text/css" href="{% bootstrap_theme_css_below_the_fold_url %}">
        <div>Deleting: {{ group.pk }} {{ group.group_name }}</div>
        <div>Are you sure you want to delete this group?</div>
        <div><b><i>Caution:</i> This will delete any links in this group.</b></div>
        <div><a href="{% url 'links:deletegroupconfirm' group.pk %}" class="btn btn-danger">Yes</a> <a href="{% url 'links:editlist' %}" class="btn btn-success">No</a>

    </body>
</html>

links/templates/links/delete_link.html
{% load bootstrap_customizer %}<!doctype html>
<html>
    <head>
        <title>Link List</title>
        <style lang="css">{% bootstrap_theme_css_above_the_fold %}</style>
    </head>
    <body>
        <link rel="stylesheet" type="text/css" href="{% bootstrap_theme_css_below_the_fold_url %}">
        <div>Deleting: {{ link.pk }} {{ link.text }} {{ link.url }}</div>
        <div>Are you sure you want to delete this link?</div>
        <div><a href="{% url 'links:deletelinkconfirm' link.pk %}" class="btn btn-danger">Yes</a> <a href="{% url 'links:editlist' %}" class="btn btn-success">No</a>

    </body>
</html>

links/templates/links/edit_list.html
{% load bootstrap_customizer %}<!doctype html>
<html>
    <head>
        <title>Link List</title>
        <style lang="css">{% bootstrap_theme_css_above_the_fold %}</style>
    </head>
    <body>
        <link rel="stylesheet" type="text/css" href="{% bootstrap_theme_css_below_the_fold_url %}">
        <div>
            <form method = "post" enctype="multipart/form-data"> 
                {% csrf_token %} 
                {{ link_form.as_p }} 
                <button type="submit" name="add_link" class="btn btn-outline-primary">Add Link</button> 
            </form> 
        </div>
        <div>
            <form method = "post" enctype="multipart/form-data"> 
                {% csrf_token %} 
                {{ group_form.as_p }} 
                <button type="submit" name="add_group" class="btn btn-outline-primary">Add Group</button> 
            </form> 
        </div>
        {% for group in groups_list %}
        <ul>{{ group.group_name }}  
            <a href="{% url 'links:movegroupup' group.pk %}" class="btn btn-outline-primary">Move Group Up</a>
            <a href="{% url 'links:movegroupdown' group.pk %}" class="btn btn-primary">Move Group Down</a>
            <a href="{% url 'links:delete_group' group.pk %}" class="btn btn-warning">Delete Group</a>
            {% for link in group.link_set.all %}
                <li><a href="{{ link.url }}">{{ link.text }}</a> 
                    <a href="{% url 'links:movelinkup' link.pk %}" class="btn btn-outline-primary">Move Link Up</a>
                    <a href="{% url 'links:movelinkdown' link.pk %}" class="btn btn-primary">Move Link Down</a>
                    <a href="{% url 'links:delete_link' link.pk %}" class="btn btn-warning">Delete Link</a> 
                </li>
            {% endfor %}
        </ul>
        {% endfor %}

        <a href="{% url 'links:index' %}">Index</a><br/>
        <a href="{% url 'admin:index' %}">Admin</a><br/>
        <a href="{% url 'logout' %}">Log Out</a><br/>
        <a href="{% url 'password_change' %}">Change Password</a>
    </body>
</html>

links/templates/links/link_list.html
{% load bootstrap_customizer %}<!doctype html>
<html>
    <head>
        <title>Link List</title>
        <style lang="css">{% bootstrap_theme_css_above_the_fold %}</style>
    </head>
    <body>
        <link rel="stylesheet" type="text/css" href="{% bootstrap_theme_css_below_the_fold_url %}">
        {% for group in groups_list %}
        <ul class="list-unstyled"><div class="lead">{{ group.group_name }}</div>
            {% for link in group.link_set.all %}
                <li><img src="{{ link.favicon }}"/>&nbsp;<a href="{{ link.url }}">{{ link.text }}</a></li>
            {% endfor %}
        </ul>
        {% endfor %}
        <a href="{% url 'links:editlist' %}">Edit List</a>
        <br/>
        <a href="{% url 'admin:index' %}">Admin</a>
    </body>
</html>

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Link List</title>{% endblock %}
</head>
<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>